module.exports = {
categoriesList:[
  {
    "South Indian": [
      "Dosa",
      "Plain Dosa",
      "Masala Dosa",
      "Onion Dosa",
      "Rava Dosa",
      "Ghee Dosa",
      "Butter Dosa",
      "Paper Dosa",
      "Set Dosa",
      "Mysore Masala Dosa",
      "Cheese Dosa",
      "Paneer Dosa",
      "Spring Roll Dosa",
      "Pizza Dosa",
      "Idli",
      "Steamed Idli",
      "Rava Idli",
      "Mini Idli",
      "Kanchipuram Idli",
      "Button Idli",
      "Fried Idli",
      "Podi Idli",
      "Vada",
      "Medu Vada",
      "Masala Vada",
      "Sabudana Vada",
      "Batata Vada",
      "Thayir Vada",
      "Uttapam",
      "Onion Uttapam",
      "Tomato Uttapam",
      "Mixed Veg Uttapam",
      "Cheese Uttapam",
      "Paneer Uttapam",
      "Rava Uttapam",
      "Other Items",
      "Upma",
      "Pongal",
      "Khichdi",
      "Bisibele Bath",
      "Lemon Rice",
      "Tamarind Rice",
      "Curd Rice",
      "Rasam Rice",
      "Pesarattu",
      "Appam",
      "Paniyaram"
    ]
  },
  {
    "North Indian": [
      "Veg Curries",
      "Dal Makhani",
      "Dal Tadka",
      "Rajma",
      "Chole",
      "Aloo Gobi",
      "Bhindi Masala",
      "Baingan Bharta",
      "Mix Veg",
      "Dum Aloo",
      "Malai Kofta",
      "Kadhai Veg",
      "Non-Veg Curries",
      "Butter Chicken",
      "Kadhai Chicken",
      "Chicken Curry",
      "Chicken Handi",
      "Chicken Tikka Masala",
      "Mutton Rogan Josh",
      "Keema Matar",
      "Egg Curry",
      "Snacks",
      "Samosa",
      "Aloo Tikki",
      "Bread Pakora",
      "Moong Dal Chilla",
      "Dhokla",
      "Methi Gota",
      "Pakoda Platter",
      "Combos & Thalis",
      "Veg Thali",
      "Non-Veg Thali",
      "Mini Thali",
      "Dal Roti Combo",
      "Rice Dal Combo",
      "Poori Bhaji Combo"
    ]
  },
  {
    "Chinese / Indo-Chinese": [
      "Noodles",
      "Veg Hakka Noodles",
      "Schezwan Noodles",
      "Egg Noodles",
      "Chicken Noodles",
      "Garlic Noodles",
      "Rice",
      "Veg Fried Rice",
      "Chicken Fried Rice",
      "Schezwan Fried Rice",
      "Triple Schezwan Rice",
      "Burnt Garlic Rice",
      "Gravies",
      "Veg Manchurian Gravy",
      "Gobi Manchurian",
      "Chilli Paneer",
      "Chilli Chicken",
      "Chicken Manchurian",
      "Schezwan Gravy",
      "Starters",
      "Spring Roll",
      "Veg Lollipop",
      "Chicken Lollipop",
      "Crispy Veg",
      "Paneer Chilli Dry",
      "Mushroom Chilli Dry",
      "Soups",
      "Manchow Soup",
      "Sweet Corn Soup",
      "Hot & Sour Soup",
      "Lemon Coriander Soup",
      "Tomato Soup"
    ]
  },
  {
    "Snacks & Chaat": [
      "Chaat",
      "Pani Puri",
      "Sev Puri",
      "Dahi Puri",
      "Bhel Puri",
      "Raj Kachori",
      "Papdi Chaat",
      "Aloo Tikki Chaat",
      "Samosa Chaat",
      "Street Snacks",
      "Vada Pav",
      "Bhaji Pav",
      "Dabeli",
      "Chilli Cheese Toast",
      "Masala Pav",
      "Mirchi Bhajji"
    ]
  },
  {
    "Rolls & Wraps": [
      "Rolls",
      "Veg Roll",
      "Egg Roll",
      "Chicken Roll",
      "Paneer Roll",
      "Aloo Tikki Roll",
      "Seekh Kebab Roll",
      "Frankie (multiple variants)"
    ]
  },
  {
    "Burgers": [
      "Veg Burgers",
      "Aloo Tikki Burger",
      "Cheese Veg Burger",
      "Paneer Tikka Burger",
      "Mexican Veg Burger",
      "Mushroom Burger",
      "Chicken Burgers",
      "Classic Chicken Burger",
      "Spicy Chicken Burger",
      "Chicken Cheese Burger",
      "Grilled Chicken Burger",
      "Specialty Burgers",
      "Double Patty Burger",
      "Peri Peri Burger",
      "Schezwan Burger",
      "Tandoori Burger"
    ]
  },
  {
    "Paneer Specialties": [
      "Curries",
      "Paneer Butter Masala",
      "Kadhai Paneer",
      "Palak Paneer",
      "Shahi Paneer",
      "Matar Paneer",
      "Paneer Lababdar",
      "Paneer Do Pyaza",
      "Paneer Bhurji",
      "Tandoori / Grilled",
      "Tandoori Paneer Tikka",
      "Achari Paneer Tikka",
      "Malai Paneer Tikka",
      "Hariyali Paneer Tikka",
      "Starters",
      "Paneer Chilli Dry",
      "Paneer 65",
      "Paneer Popcorn",
      "Paneer Pakora",
      "Crispy Paneer"
    ]
  },
  {
    "Indian Breads": [
      "Naan & Kulcha",
      "Plain Naan",
      "Butter Naan",
      "Garlic Naan",
      "Stuffed Naan (Paneer/Onion/Keema)",
      "Amritsari Kulcha",
      "Roti & Paratha",
      "Tandoori Roti",
      "Phulka",
      "Aloo Paratha",
      "Gobi Paratha",
      "Methi Paratha",
      "Laccha Paratha",
      "Puri & Bhatura",
      "Poori",
      "Bedmi Puri",
      "Chole Bhature",
      "Luchi"
    ]
  },
  {
    "Desserts & Sweets": [
      "Indian Sweets",
      "Gulab Jamun",
      "Rasgulla",
      "Rasmalai",
      "Jalebi",
      "Imarti",
      "Kaju Katli",
      "Soan Papdi",
      "Ladoo (Boondi, Motichoor)",
      "Peda",
      "Sandesh",
      "Other Desserts",
      "Gajar Halwa",
      "Moong Dal Halwa",
      "Rabri",
      "Basundi",
      "Phirni",
      "Malpua",
      "Kheer",
      "Sheer Khurma",
      "Ice Cream & Kulfi",
      "Vanilla",
      "Chocolate",
      "Butterscotch",
      "Rajbhog",
      "Kesar Pista",
      "Matka Kulfi",
      "Mango Kulfi"
    ]
  },
  {
    "Beverages": [
      "Beverages",
      "Hot Beverages",
      "Masala Chai",
      "Cutting Chai",
      "Ginger Tea",
      "Green Tea",
      "Filter Coffee",
      "Espresso",
      "Cold Beverages",
      "Iced Tea",
      "Cold Coffee",
      "Cold Cocoa",
      "Lemonade",
      "Buttermilk (Chaas)",
      "Jaljeera",
      "Aam Panna",
      "Shakes & Smoothies",
      "Chocolate Shake",
      "Strawberry Shake",
      "Banana Shake",
      "Mango Smoothie",
      "Mixed Fruit Smoothie",
      "Lassi",
      "Sweet Lassi",
      "Salted Lassi",
      "Mango Lassi",
      "Rose Lassi"
    ]
  },
  {
    "Pizza": [
      "Pizza",
      "Margherita Pizza",
      "Veggie Pizza",
      "Paneer Tikka Pizza",
      "Chicken Tikka Pizza",
      "BBQ Chicken Pizza",
      "Pepperoni Pizza",
      "Four Cheese Pizza",
      "Mexican Green Wave Pizza"
    ]
  },
  {
    "Pasta": [
      "Pasta",
      "Veg Pasta",
      "Alfredo Pasta",
      "Tomato Basil Pasta",
      "Arrabbiata Pasta",
      "White Sauce Pasta",
      "Penne Pasta",
      "Spaghetti Pasta",
      "Macaroni Pasta"
    ]
  },
  {
    "Biryani": [
      "Biryani",
      "Chicken Dum Biryani",
      "Kolkata Chicken Biryani",
      "Lucknowi Chicken Biryani",
      "Malabar Chicken Biryani",
      "Sindhi Chicken Biryani",
      "Chettinad Chicken Biryani",
      "Mughlai Chicken Biryani",
      "Donne Chicken Biryani",
      "Ambur Chicken Biryani",
      "Thalassery Chicken Biryani",
      "Mutton Dum Biryani",
      "Lucknowi Mutton Biryani",
      "Kolkata Mutton Biryani",
      "Malabar Mutton Biryani",
      "Ambur Mutton Biryani",
      "Bohri Mutton Biryani",
      "Kashmiri Yakhni Mutton Biryani",
      "Veg Dum Biryani",
      "Paneer Biryani",
      "Kathal Biryani",
      "Mushroom Biryani",
      "Soya Chunk Biryani",
      "Mix Veg Mughlai Biryani",
      "Corn and Capsicum Biryani",
      "Egg Biryani",
      "Fish Biryani",
      "Prawns Biryani",
      "Crab Biryani",
      "Keema Biryani",
      "Afghani Biryani",
      "Arabian Mandi",
      "Burmese Biryani",
      "Tandoori Chicken Biryani",
      "Nizami Biryani"
    ]
  },
  {
    "Sandwich": [
      "Sandwich",
      "Veg Sandwich",
      "Grilled Cheese Sandwich",
      "Paneer Tikka Sandwich",
      "Club Sandwich",
      "Cheese Chilli Sandwich",
      "Corn and Spinach Sandwich",
      "Aloo Sandwich",
      "Chicken Sandwich",
      "Egg Sandwich",
      "Tandoori Chicken Sandwich",
      "Peri Peri Sandwich",
      "Bombay Masala Sandwich",
      "Coleslaw Sandwich",
      "Tuna Sandwich",
      "BLT Sandwich",
      "Ham and Cheese Sandwich",
      "Peanut Butter Sandwich",
      "Nutella Sandwich"
    ]
  },
  {
    "Coffee": [
      "Coffee",
      "Espresso",
      "Americano",
      "Cappuccino",
      "Latte",
      "Mocha",
      "Macchiato",
      "Cold Coffee",
      "Iced Latte",
      "Filter Coffee",
      "Turkish Coffee",
      "Irish Coffee",
      "Affogato",
      "Flat White",
      "Dalgona Coffee",
      "Instant Coffee",
      "Black Coffee",
      "Café au Lait",
      "Nitro Coffee"
    ]
  },
  {
    "Ice Cream": [
      "Ice Cream",
      "Vanilla Ice Cream",
      "Chocolate Ice Cream",
      "Strawberry Ice Cream",
      "Butterscotch Ice Cream",
      "Mango Ice Cream",
      "Black Currant Ice Cream",
      "Cookies and Cream Ice Cream",
      "Mint Chocolate Chip Ice Cream",
      "Pista Ice Cream",
      "Kesar Pista Ice Cream",
      "Choco Chip Ice Cream",
      "Caramel Ice Cream",
      "Coffee Ice Cream",
      "Tutti Frutti Ice Cream",
      "Kulfi",
      "Malai Kulfi",
      "Matka Kulfi",
      "Falooda Ice Cream",
      "Belgian Chocolate Ice Cream"
    ]
  },
  {
    "Cake": [
      "Cake",
      "Chocolate Cake",
      "Vanilla Cake",
      "Red Velvet Cake",
      "Black Forest Cake",
      "Butterscotch Cake",
      "Cheesecake",
      "Carrot Cake",
      "Pineapple Cake",
      "Coffee Cake",
      "Lemon Drizzle Cake",
      "Strawberry Shortcake",
      "Funfetti Cake",
      "Banana Cake",
      "Chocolate Fudge Cake",
      "Blueberry Cake",
      "Coffee Walnut Cake",
      "Opera Cake",
      "Tiramisu Cake",
      "Fruit Cake"
    ]
  },
  {
    "Momos": [
      "Momos",
      "Steamed Veg Momos",
      "Steamed Chicken Momos",
      "Fried Momos",
      "Kothey Momos",
      "Tandoori Momos",
      "Chili Momos",
      "Soup Momos",
      "Paneer Momos",
      "Cheese Momos",
      "Jain Momos",
      "Pork Momos",
      "Buff Momos",
      "Mushroom Momos",
      "Garlic Momos",
      "Schezwan Momos"
    ]
  },
  {
    "Khichdi": [
      "Khichdi",
      "Moong Dal Khichdi",
      "Masala Khichdi",
      "Pongal",
      "Sabudana Khichdi",
      "Palak Khichdi",
      "Vegetable Khichdi",
      "Gujarati Khichdi",
      "Toor Dal Khichdi",
      "Bajra Khichdi",
      "Brown Rice Khichdi",
      "Panchmel Khichdi",
      "Bhuni Khichdi",
      "Methi Khichdi",
      "Dalia Khichdi",
      "Lauki Khichdi"
    ]
  },
  {
    "Noodles": [
      "Noodles",
      "Hakka Noodles",
      "Chow Mein",
      "Schezwan Noodles",
      "Vegetable Noodles",
      "Chicken Noodles",
      "Egg Noodles",
      "Singapore Noodles",
      "Garlic Noodles",
      "Cold Noodles",
      "Rice Noodles",
      "Pad Thai",
      "Lo Mein",
      "Shanghai Noodles",
      "Udon Noodles",
      "Ramen Noodles",
      "Soba Noodles"
    ]
  },
  {
    "Thali": [
      "Thali",
      "North Indian Thali",
      "South Indian Thali",
      "Rajasthani Thali",
      "Gujarati Thali",
      "Punjabi Thali",
      "Maharashtrian Thali",
      "Bengali Thali",
      "Mughlai Thali",
      "Kashmiri Thali",
      "Goan Thali",
      "Kerala Sadya",
      "Hyderabadi Thali",
      "Bihari Thali",
      "Malvani Thali",
      "Awadhi Thali"
    ]
  },
  {
    "Fries": [
      "Fries",
      "Classic French Fries",
      "Curly Fries",
      "Waffle Fries",
      "Shoestring Fries",
      "Crinkle-Cut Fries",
      "Steak Fries",
      "Sweet Potato Fries",
      "Garlic Fries",
      "Cheese Fries",
      "Chili Cheese Fries",
      "Masala Fries",
      "Peri Peri Fries",
      "Truffle Fries",
      "Loaded Fries",
      "Spicy Cajun Fries"
    ]
  },
  {
  "Rice": [
    "Steamed Rice",
    "Jeera Rice",
    "Fried Rice",
    "Veg Pulao",
    "Peas Pulao",
    "Kashmiri Pulao",
    "Tamarind Rice",
    "Lemon Rice",
    "Curd Rice",
    "Tomato Rice",
    "Ghee Rice",
    "Coconut Rice",
    "Masala Rice",
    "Schezwan Fried Rice",
    "Egg Fried Rice",
    "Chicken Fried Rice",
    "Mutton Pulao",
    "Bisi Bele Bath"
  ]
}
]
}