var mongoose = require('mongoose');
var settingsSchema = new mongoose.Schema({
  androidVersion: String,
  iosVersion: String,
  message: { type: String, default: "Please install our latest app for new features." },
  terms: { type: String, default: "https://kikokids.in/termsofuse.html" },
  privacy: { type: String, default: "https://kikokids.in/privacy_policy.html" },
  enable_states: [],
  isHardUpdate: { type: String, default: false },
  rtmp_link: String,
  disclamer: String,
  faq: String,
  return: String,
  videoLimit: Number,
  iosLink: String,
  androidLink: String,
  delivery: String,
  timeout: Number,
  sellerReward: Boolean,
  rewardMessage: String,
  razor_key_id: String,
  changeNumberDelayDuration: Number,
  changeNumberIsDelay: { type: String, default: true },
  sdkKeyForAndroid: { type: String },
  sdkKeyForIos: { type: String },
  coinRupeesRatio: { type: Number },
  bonusFrequency: { type: Number },
  walletOffer: { type: String },
  orderPageTermsAndCondition: { type: Array },
  orderPageTermsAndConditionForBuyer: { type: Array },
  customerListingSellerEnable: { type: Boolean },
  addStoreDemoLink: { type: String },
  getDeliveryDemoLink: { type: String },
  freeDeliveryFlag: { type: Boolean },
  maxFreeDeliveryInOneDay: { type: Number },
  freeDeliveryCredit: { type: Number },
  borzoDeliveryEnable: { type: Boolean },
  dunzoDeliveryEnable: { type: Boolean },
  buyerOrdersEnable: { type: Boolean },
  sellerOrdersEnable: { type: Boolean },
  minimumRechargeAmount: { type: Number },
  kochavaAndroidKey: { type: String },
  kochavaIosKey: { type: String },
  uxCamApiKey: { type: String },
  buyerOrderExpiresTime: { type: Number },
  hearAboutUsOptions: { type: Array },
  supportCenterNumber: { type: String },
  supportCenterWhatsAppNumber: { type: String },
  ondcCommision: { type: Object },
  ondcSettings: { type: Object }
});
module.exports = mongoose.model('appsettings', settingsSchema);
